-- acidburn highlight definitions
local M = {}

function M.setup(c, opts)
  opts = opts or {}
  local none = c.none

  -- helpers -----------------------------------------------------------------
  local italic  = opts.italic_comments == false and {} or { italic = true }
  local bold    = opts.bold_keywords == false and {} or { bold = true }
  local ui_bg   = opts.transparent and none or c.bg
  local dark_bg = opts.transparent and none or c.bg_dark

  local hl = {
    -- Editor UI --------------------------------------------------------------
    Normal          = { fg = c.fg, bg = ui_bg },
    NormalNC        = { fg = c.fg, bg = ui_bg },
    NormalFloat     = { fg = c.fg, bg = dark_bg },
    FloatBorder     = { fg = c.bg_border, bg = dark_bg },
    FloatTitle      = { fg = c.green, bg = dark_bg, bold = true },
    ColorColumn     = { bg = c.bg_alt },
    Conceal         = { fg = c.fg_dim },
    Cursor          = { fg = c.bg, bg = c.green },
    lCursor         = { fg = c.bg, bg = c.green },
    CursorIM        = { fg = c.bg, bg = c.green },
    CursorLine      = { bg = c.bg_high },
    CursorColumn    = { bg = c.bg_high },
    CursorLineNr    = { fg = c.yellow, bold = true },
    LineNr          = { fg = c.fg_faint },
    LineNrAbove     = { fg = c.fg_faint },
    LineNrBelow     = { fg = c.fg_faint },
    SignColumn      = { fg = c.fg_dim, bg = ui_bg },
    FoldColumn      = { fg = c.fg_faint, bg = ui_bg },
    Folded          = { fg = c.cyan, bg = c.bg_high },
    VertSplit       = { fg = c.bg_border },
    WinSeparator    = { fg = c.bg_border },
    MatchParen      = { fg = c.pink, bold = true, underline = true },
    NonText         = { fg = c.fg_faint },
    Whitespace      = { fg = c.bg_sel },
    SpecialKey      = { fg = c.bg_border },
    EndOfBuffer     = { fg = c.bg },

    Visual          = { bg = c.bg_sel },
    VisualNOS       = { bg = c.bg_sel },
    Search          = { fg = c.bg, bg = c.yellow, bold = true },
    IncSearch       = { fg = c.bg, bg = c.orange, bold = true },
    CurSearch       = { fg = c.bg, bg = c.pink, bold = true },
    Substitute      = { fg = c.bg, bg = c.pink },

    Pmenu           = { fg = c.fg, bg = dark_bg },
    PmenuSel        = { fg = c.bg, bg = c.green, bold = true },
    PmenuKind       = { fg = c.purple, bg = dark_bg },
    PmenuKindSel    = { fg = c.bg, bg = c.green },
    PmenuExtra      = { fg = c.fg_dim, bg = dark_bg },
    PmenuExtraSel   = { fg = c.bg, bg = c.green },
    PmenuSbar       = { bg = c.bg_alt },
    PmenuThumb      = { bg = c.green },
    WildMenu        = { fg = c.bg, bg = c.green },

    StatusLine      = { fg = c.fg, bg = dark_bg },
    StatusLineNC    = { fg = c.fg_faint, bg = dark_bg },
    TabLine         = { fg = c.fg_dim, bg = dark_bg },
    TabLineFill     = { bg = dark_bg },
    TabLineSel      = { fg = c.bg, bg = c.green, bold = true },

    ModeMsg         = { fg = c.green, bold = true },
    MsgArea         = { fg = c.fg },
    MoreMsg         = { fg = c.cyan },
    Question        = { fg = c.green },
    ErrorMsg        = { fg = c.red, bold = true },
    WarningMsg      = { fg = c.amber, bold = true },
    Title           = { fg = c.green, bold = true },
    Directory       = { fg = c.blue, bold = true },
    QuickFixLine    = { bg = c.bg_high, bold = true },
    SpellBad        = { sp = c.red, undercurl = true },
    SpellCap        = { sp = c.amber, undercurl = true },
    SpellRare       = { sp = c.purple, undercurl = true },
    SpellLocal      = { sp = c.cyan, undercurl = true },
    WinBar          = { fg = c.fg, bg = ui_bg },
    WinBarNC        = { fg = c.fg_dim, bg = ui_bg },

    -- Syntax (legacy vim groups) --------------------------------------------
    Comment        = vim.tbl_extend("force", { fg = c.green_lo }, italic),

    Constant       = { fg = c.cyan },
    String         = { fg = c.salmon },
    Character      = { fg = c.salmon },
    Number         = { fg = c.cyan },
    Float          = { fg = c.cyan },
    Boolean        = { fg = c.orange, bold = true },

    Identifier     = { fg = c.fg },
    Function       = { fg = c.green, bold = true },

    Statement      = vim.tbl_extend("force", { fg = c.yellow }, bold),
    Conditional    = vim.tbl_extend("force", { fg = c.yellow }, bold),
    Repeat         = vim.tbl_extend("force", { fg = c.yellow }, bold),
    Label          = { fg = c.yellow },
    Operator       = { fg = c.orange },
    Keyword        = vim.tbl_extend("force", { fg = c.yellow }, bold),
    Exception      = { fg = c.red, bold = true },

    PreProc        = { fg = c.purple },
    Include        = { fg = c.purple, bold = true },
    Define         = { fg = c.purple },
    Macro          = { fg = c.pink },
    PreCondit      = { fg = c.purple },

    Type           = { fg = c.purple, bold = true },
    StorageClass   = { fg = c.yellow },
    Structure      = { fg = c.purple },
    Typedef        = { fg = c.purple },

    Special        = { fg = c.pink },
    SpecialChar    = { fg = c.pink },
    Tag            = { fg = c.green },
    Delimiter      = { fg = c.fg_dim },
    SpecialComment = { fg = c.green_lo, bold = true },
    Debug          = { fg = c.red },

    Underlined     = { fg = c.blue, underline = true },
    Ignore         = { fg = c.fg_faint },
    Error          = { fg = c.red, bold = true },
    Todo           = { fg = c.bg, bg = c.yellow, bold = true },

    -- Diagnostics -----------------------------------------------------------
    DiagnosticError            = { fg = c.red },
    DiagnosticWarn             = { fg = c.amber },
    DiagnosticInfo             = { fg = c.blue },
    DiagnosticHint             = { fg = c.cyan },
    DiagnosticOk               = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.diff_delete },
    DiagnosticVirtualTextWarn  = { fg = c.amber, bg = c.bg_high },
    DiagnosticVirtualTextInfo  = { fg = c.blue, bg = c.bg_high },
    DiagnosticVirtualTextHint  = { fg = c.cyan, bg = c.bg_high },
    DiagnosticUnderlineError   = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn    = { sp = c.amber, undercurl = true },
    DiagnosticUnderlineInfo    = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint    = { sp = c.cyan, undercurl = true },
    DiagnosticUnnecessary      = { fg = c.fg_faint, italic = true },
    DiagnosticDeprecated       = { fg = c.fg_dim, strikethrough = true },

    -- LSP -------------------------------------------------------------------
    LspReferenceText           = { bg = c.bg_sel },
    LspReferenceRead           = { bg = c.bg_sel },
    LspReferenceWrite          = { bg = c.bg_sel, underline = true },
    LspSignatureActiveParameter= { fg = c.orange, bold = true },
    LspCodeLens                = { fg = c.fg_faint, italic = true },
    LspInlayHint               = { fg = c.fg_faint, bg = c.bg_alt, italic = true },

    -- Treesitter ------------------------------------------------------------
    ["@comment"]             = { link = "Comment" },
    ["@comment.error"]       = { fg = c.bg, bg = c.red, bold = true },
    ["@comment.warning"]     = { fg = c.bg, bg = c.amber, bold = true },
    ["@comment.note"]        = { fg = c.bg, bg = c.cyan, bold = true },
    ["@comment.todo"]        = { link = "Todo" },

    ["@constant"]            = { fg = c.cyan },
    ["@constant.builtin"]    = { fg = c.pink, bold = true },
    ["@constant.macro"]      = { fg = c.pink },
    ["@number"]              = { fg = c.cyan },
    ["@number.float"]        = { fg = c.cyan },
    ["@boolean"]             = { fg = c.orange, bold = true },
    ["@character"]           = { fg = c.salmon },
    ["@character.special"]   = { fg = c.pink },

    ["@string"]              = { fg = c.salmon },
    ["@string.regexp"]       = { fg = c.pink },
    ["@string.escape"]       = { fg = c.pink, bold = true },
    ["@string.special"]      = { fg = c.pink },
    ["@string.special.url"]  = { fg = c.blue, underline = true },
    ["@string.documentation"]= { fg = c.green_lo },

    ["@function"]            = { fg = c.green, bold = true },
    ["@function.builtin"]    = { fg = c.lime, bold = true },
    ["@function.call"]       = { fg = c.green },
    ["@function.macro"]      = { fg = c.pink },
    ["@function.method"]     = { fg = c.lime, bold = true },
    ["@function.method.call"]= { fg = c.lime },
    ["@constructor"]         = { fg = c.purple, bold = true },

    ["@keyword"]             = vim.tbl_extend("force", { fg = c.yellow }, bold),
    ["@keyword.function"]    = vim.tbl_extend("force", { fg = c.yellow }, bold),
    ["@keyword.operator"]    = { fg = c.orange, bold = true },
    ["@keyword.return"]      = { fg = c.red, bold = true },
    ["@keyword.conditional"] = vim.tbl_extend("force", { fg = c.yellow }, bold),
    ["@keyword.repeat"]      = vim.tbl_extend("force", { fg = c.yellow }, bold),
    ["@keyword.import"]      = { fg = c.purple, bold = true },
    ["@keyword.exception"]   = { fg = c.red, bold = true },
    ["@keyword.directive"]   = { fg = c.purple },
    ["@keyword.coroutine"]   = { fg = c.pink, bold = true },

    ["@operator"]            = { fg = c.orange },

    ["@variable"]            = { fg = c.fg },
    ["@variable.builtin"]    = { fg = c.pink, bold = true },
    ["@variable.parameter"]  = { fg = c.blue },
    ["@variable.member"]     = { fg = c.lime },

    ["@property"]            = { fg = c.lime },
    ["@field"]              = { fg = c.lime },

    ["@type"]                = { fg = c.purple, bold = true },
    ["@type.builtin"]        = { fg = c.purple },
    ["@type.definition"]     = { fg = c.purple, bold = true },
    ["@type.qualifier"]      = { fg = c.yellow },
    ["@attribute"]           = { fg = c.amber },

    ["@module"]              = { fg = c.cyan },
    ["@namespace"]           = { fg = c.cyan },

    ["@punctuation.delimiter"]  = { fg = c.fg_dim },
    ["@punctuation.bracket"]    = { fg = c.amber },
    ["@punctuation.special"]    = { fg = c.pink },

    ["@tag"]                 = { fg = c.yellow, bold = true },
    ["@tag.builtin"]         = { fg = c.yellow, bold = true },
    ["@tag.attribute"]       = { fg = c.green },
    ["@tag.delimiter"]       = { fg = c.fg_dim },

    ["@label"]               = { fg = c.pink },
    ["@markup.heading"]      = { fg = c.green, bold = true },
    ["@markup.heading.1"]    = { fg = c.green, bold = true },
    ["@markup.heading.2"]    = { fg = c.yellow, bold = true },
    ["@markup.heading.3"]    = { fg = c.cyan, bold = true },
    ["@markup.heading.4"]    = { fg = c.purple, bold = true },
    ["@markup.strong"]       = { fg = c.orange, bold = true },
    ["@markup.italic"]       = { fg = c.salmon, italic = true },
    ["@markup.strikethrough"]= { fg = c.fg_dim, strikethrough = true },
    ["@markup.underline"]    = { underline = true },
    ["@markup.raw"]          = { fg = c.cyan },
    ["@markup.raw.block"]    = { fg = c.cyan },
    ["@markup.link"]         = { fg = c.blue, underline = true },
    ["@markup.link.label"]   = { fg = c.pink },
    ["@markup.link.url"]     = { fg = c.blue, underline = true },
    ["@markup.list"]         = { fg = c.orange },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"]= { fg = c.fg_dim },
    ["@markup.quote"]        = { fg = c.green_lo, italic = true },
    ["@markup.math"]         = { fg = c.cyan },

    ["@diff.plus"]           = { fg = c.green },
    ["@diff.minus"]          = { fg = c.red },
    ["@diff.delta"]          = { fg = c.blue },

    -- LSP semantic tokens ---------------------------------------------------
    ["@lsp.type.class"]         = { link = "@type" },
    ["@lsp.type.decorator"]     = { link = "@attribute" },
    ["@lsp.type.enum"]          = { link = "@type" },
    ["@lsp.type.enumMember"]    = { link = "@constant" },
    ["@lsp.type.function"]      = { link = "@function" },
    ["@lsp.type.interface"]     = { link = "@type" },
    ["@lsp.type.macro"]         = { link = "@function.macro" },
    ["@lsp.type.method"]        = { link = "@function.method" },
    ["@lsp.type.namespace"]     = { link = "@module" },
    ["@lsp.type.parameter"]     = { link = "@variable.parameter" },
    ["@lsp.type.property"]      = { link = "@property" },
    ["@lsp.type.struct"]        = { link = "@type" },
    ["@lsp.type.type"]          = { link = "@type" },
    ["@lsp.type.variable"]      = { link = "@variable" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },

    -- Git / diff ------------------------------------------------------------
    DiffAdd         = { bg = c.diff_add },
    DiffChange      = { bg = c.diff_change },
    DiffDelete      = { bg = c.diff_delete },
    DiffText        = { bg = c.diff_text, bold = true },
    diffAdded       = { fg = c.green },
    diffRemoved     = { fg = c.red },
    diffChanged     = { fg = c.blue },
    diffLine        = { fg = c.purple },
    diffFile        = { fg = c.yellow },
    diffNewFile     = { fg = c.green },
    diffOldFile     = { fg = c.red },

    -- gitsigns
    GitSignsAdd      = { fg = c.green },
    GitSignsChange   = { fg = c.blue },
    GitSignsDelete   = { fg = c.red },
    GitSignsAddNr    = { fg = c.green },
    GitSignsChangeNr = { fg = c.blue },
    GitSignsDeleteNr = { fg = c.red },
    GitSignsCurrentLineBlame = { fg = c.fg_faint, italic = true },

    -- Telescope -------------------------------------------------------------
    TelescopeNormal        = { fg = c.fg, bg = dark_bg },
    TelescopeBorder        = { fg = c.bg_border, bg = dark_bg },
    TelescopePromptNormal  = { fg = c.fg, bg = c.bg_high },
    TelescopePromptBorder  = { fg = c.bg_high, bg = c.bg_high },
    TelescopePromptTitle   = { fg = c.bg, bg = c.pink, bold = true },
    TelescopePromptPrefix  = { fg = c.green },
    TelescopeResultsTitle  = { fg = c.bg, bg = c.green, bold = true },
    TelescopePreviewTitle  = { fg = c.bg, bg = c.cyan, bold = true },
    TelescopeSelection     = { fg = c.fg_bright, bg = c.bg_sel, bold = true },
    TelescopeSelectionCaret= { fg = c.pink, bg = c.bg_sel },
    TelescopeMatching      = { fg = c.yellow, bold = true },

    -- nvim-cmp --------------------------------------------------------------
    CmpItemAbbr             = { fg = c.fg },
    CmpItemAbbrDeprecated   = { fg = c.fg_faint, strikethrough = true },
    CmpItemAbbrMatch        = { fg = c.yellow, bold = true },
    CmpItemAbbrMatchFuzzy   = { fg = c.yellow, bold = true },
    CmpItemMenu             = { fg = c.fg_faint, italic = true },
    CmpItemKindText         = { fg = c.fg },
    CmpItemKindFunction     = { fg = c.green },
    CmpItemKindMethod       = { fg = c.lime },
    CmpItemKindConstructor  = { fg = c.purple },
    CmpItemKindVariable     = { fg = c.blue },
    CmpItemKindKeyword      = { fg = c.yellow },
    CmpItemKindClass        = { fg = c.purple },
    CmpItemKindInterface    = { fg = c.purple },
    CmpItemKindProperty     = { fg = c.lime },
    CmpItemKindField        = { fg = c.lime },
    CmpItemKindEnum         = { fg = c.purple },
    CmpItemKindSnippet      = { fg = c.pink },
    CmpItemKindConstant     = { fg = c.cyan },
    CmpItemKindModule       = { fg = c.cyan },
    CmpItemKindColor        = { fg = c.orange },
    CmpItemKindFile         = { fg = c.blue },
    CmpItemKindFolder       = { fg = c.blue },

    -- blink.cmp
    BlinkCmpMenu            = { fg = c.fg, bg = dark_bg },
    BlinkCmpMenuBorder      = { fg = c.bg_border, bg = dark_bg },
    BlinkCmpMenuSelection   = { bg = c.bg_sel, bold = true },
    BlinkCmpLabelMatch      = { fg = c.yellow, bold = true },
    BlinkCmpKind            = { fg = c.purple },

    -- nvim-tree / neo-tree --------------------------------------------------
    NvimTreeNormal          = { fg = c.fg, bg = dark_bg },
    NvimTreeFolderName      = { fg = c.blue },
    NvimTreeFolderIcon      = { fg = c.blue },
    NvimTreeOpenedFolderName= { fg = c.blue, bold = true },
    NvimTreeRootFolder      = { fg = c.pink, bold = true },
    NvimTreeGitDirty        = { fg = c.amber },
    NvimTreeGitNew          = { fg = c.green },
    NvimTreeGitDeleted      = { fg = c.red },
    NvimTreeSpecialFile     = { fg = c.pink, underline = true },
    NvimTreeIndentMarker    = { fg = c.bg_border },
    NvimTreeExecFile        = { fg = c.green, bold = true },
    NvimTreeImageFile       = { fg = c.purple },

    NeoTreeNormal           = { fg = c.fg, bg = dark_bg },
    NeoTreeNormalNC         = { fg = c.fg, bg = dark_bg },
    NeoTreeDirectoryName    = { fg = c.blue },
    NeoTreeDirectoryIcon    = { fg = c.blue },
    NeoTreeRootName         = { fg = c.pink, bold = true },
    NeoTreeGitAdded         = { fg = c.green },
    NeoTreeGitModified      = { fg = c.amber },
    NeoTreeGitDeleted       = { fg = c.red },
    NeoTreeIndentMarker     = { fg = c.bg_border },

    -- WhichKey --------------------------------------------------------------
    WhichKey                = { fg = c.pink, bold = true },
    WhichKeyGroup           = { fg = c.blue },
    WhichKeyDesc            = { fg = c.fg },
    WhichKeySeparator       = { fg = c.fg_faint },
    WhichKeyFloat           = { bg = dark_bg },
    WhichKeyBorder          = { fg = c.bg_border, bg = dark_bg },

    -- indent-blankline ------------------------------------------------------
    IblIndent               = { fg = c.bg_high },
    IblScope                = { fg = c.pink },
    IblWhitespace           = { fg = c.bg_high },

    -- notify / noice --------------------------------------------------------
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder  = { fg = c.amber },
    NotifyINFOBorder  = { fg = c.cyan },
    NotifyDEBUGBorder = { fg = c.fg_dim },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORTitle  = { fg = c.red, bold = true },
    NotifyWARNTitle   = { fg = c.amber, bold = true },
    NotifyINFOTitle   = { fg = c.cyan, bold = true },
    NotifyDEBUGTitle  = { fg = c.fg_dim },
    NotifyTRACETitle  = { fg = c.purple, bold = true },
    NoiceCmdlinePopupBorder = { fg = c.pink },
    NoiceCmdlineIcon        = { fg = c.green },

    -- mini.nvim -------------------------------------------------------------
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.cyan, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.pink, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniIconsGreen  = { fg = c.green },
    MiniIconsBlue   = { fg = c.blue },
    MiniIconsCyan   = { fg = c.cyan },
    MiniIconsRed    = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },
    MiniIconsOrange = { fg = c.orange },
    MiniIconsPurple = { fg = c.purple },
    MiniIconsGrey   = { fg = c.fg_dim },

    -- Flash / Leap / Hop ----------------------------------------------------
    FlashLabel      = { fg = c.bg, bg = c.pink, bold = true },
    FlashMatch      = { fg = c.bg, bg = c.cyan },
    LeapLabelPrimary= { fg = c.bg, bg = c.pink, bold = true },
    HopNextKey      = { fg = c.pink, bold = true },
    HopNextKey1     = { fg = c.cyan, bold = true },
    HopNextKey2     = { fg = c.blue },

    -- dashboard / alpha -----------------------------------------------------
    DashboardHeader   = { fg = c.green, bold = true },
    DashboardFooter   = { fg = c.green_lo, italic = true },
    DashboardShortCut = { fg = c.pink },
    DashboardDesc     = { fg = c.cyan },
    AlphaHeader       = { fg = c.green, bold = true },
    AlphaButtons      = { fg = c.cyan },
    AlphaShortcut     = { fg = c.pink },
    AlphaFooter       = { fg = c.green_lo, italic = true },

    -- Terminal colors are set in init.lua
  }

  return hl
end

return M
